version: '2'
services:
    tabletennismanager-app:
        image: tabletennismanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tabletennismanager-mysql:3306/tabletennismanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tabletennismanager-mysql:
        extends:
            file: mysql.yml
            service: tabletennismanager-mysql
